# Generated by Django 5.1.4 on 2024-12-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_questionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
